# Download Full Installer Opencore HP Zbook 15 G2 - 0.8.0

VNSafes Chia sẻ cho anh em bộ cài đặt macOS Monterey Opencore dành cho HP Zbook 15 G2 và Dell M4800, ae nào chung cấu hình với mình thì có thể tải về chơi nhé.                                      
Cấu hình máy: Zbook 15. G2 & Dell Precision M4800.        
CPU: Core I7 4810 QM                                                                       
Đây là bộ EFI mình tự build chuẩn nhất hệ mặt trời 😁, Dell M4800 chỉ cần chỉnh sửa config.plist một chút là có thể chạy nhé.                               
Link Down Full Installer: 
https://drive.google.com/drive/u/2/folders/1D2aPrGwLULIiQi9aHAe_f1NG5pIVAHx4
